### ISSUE TITLE
Špatné otázky a odpovědi - Quiz na programování

### ISSUE THREAD

**Issue by RadekPelikan** [Akino02/quiz#4]
Quiz na programování:
- Otázka 4: v Pythonu je deklarace proměnné. V pythonu se deklarují proměnné bez datového typu, protože je to dynamicky typovaný jazyk, ale to neznamená, že nemá deklaraci proměnné. Lepší otázka by byla: "Python je programovací jazyk", "staticky typovaný", "dynamicky typovaný"
  - [W3schools](https://www.w3schools.com/python/python_variables.asp)
  - [Stackoverflow declaration definition](https://stackoverflow.com/questions/1410563/what-is-the-difference-between-a-definition-and-a-declaration)
- Otázka 6: v Pythonu // operátor slouží pro vydělení a zaokrouhlení dolů (floor), takže `7 // 2 == 3`
  - [W3schools](https://www.w3schools.com/python/python_operators.asp)
- Otázka 17: Datový typ pro desetinná čísla je i double i float
  - [W3chools](https://www.w3schools.com/java/java_data_types.asp)

**Comment by Akino02** [comment]
Děkuji za nalezení chyb. Občas se stane, že přemýšlím nad jinými věcmi a napíšu tam chybu, ale tyto chyby jsem si neuvědomil.

Chyby budou opraveny co nejdříve.

Děkuji

**Comment by Akino02** [comment]
> Opravy

- Otázka 4: "Je povinností psát datový typ při tvoření nové proměnné v deklaraci ? (Python)".
- Otázka 6: "Jak se zapisuje dělení se zbytkem v Pythonu ?".
- Otázka 17: Tady jsem pouze přidal správnou odpověď.
